version: '3'
services:
  influxdb:
    image: influxdb:1.7.11
    container_name: influxdb
    env_file:
      - ./.env
    ports:
      - '8086:8086'
      - '9999:9999'
    volumes:
      - ./influxdb-storage:/var/lib/influxdb:rw
      - ./influxdb.conf:/etc/influxdb/influxdb.conf
      - ./influxdb-selfsigned.key:/etc/ssl/private/influxdb-selfsigned.key:ro
      - ./influxdb-selfsigned.crt:/etc/ssl/certs/influxdb-selfsigned.crt:ro
    environment:
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_NAME}
      - INFLUXDB_ADMIN_PASSWORD="${INFLUXDB_ADMIN_PASSWORD}"
      - INFLUXDB_USER=${INFLUXDB_USER_NAME}
      - INFLUXDB_USER_PASSWORD=${INFLUXDB_USER_PASSWORD}
  chronograf:
    image: chronograf:latest
    container_name: chronograf
    ports:
      - '127.0.0.1:8888:8888'
    volumes:
      - ./chronograf-storage:/var/lib/chronograf:rw
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=https://influxdb:8086
      - INFLUXDB_USERNAME=${INFLUXDB_ADMIN_NAME}
      - INFLUXDB_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - '3000:3000'
    volumes:
      - ./grafana-storage:/var/lib/grafana:rw
      - ./grafana-provisioning/:/etc/grafana/provisioning
      - ./influxdb-selfsigned.key:/etc/ssl/private/influxdb-selfsigned.key:rw
      - ./influxdb-selfsigned.crt:/etc/ssl/certs/influxdb-selfsigned.crt:ro
      - ./grafana.ini:/etc/grafana/grafana.ini:ro
      - ./plugins:/var/lib/grafana/plugins
    depends_on:
      - influxdb
  n_puzzle:
    build: .
    container_name: n_puzzle
    hostname: n_puzzle
    env_file:
      - .env
    ports:
      - '2222:22'
    # networks:
    # devices:
    volumes:
      - ./n-puzzle:/home/user/n-puzzle:rw
    entrypoint: tail -f /dev/null
    working_dir: /home/user/n-puzzle
    user: user
