{
 "title": "Average number of solution moves.",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "DFS Random",
   "type": "table",
   "gridPos": { "h": 18, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "project=n-puzzle",
     "query": "SELECT mean(\"solution_moves\") AS \"Moves\" , count(\"solution_moves\") AS \"Num of solutions\" FROM \"project=n-puzzle\" WHERE (\"puzzle_size\" = '3' AND \"algorithm\" = 'dfs' AND \"algorithm_substring\" = 'no_mem_rand') AND $timeFilter GROUP BY time(1h)",
     "select": [
      [
       { "params": [ "solution_moves" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "solution_moves" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "puzzle_size", "operator": "=", "value": "3" },
      { "condition": "AND", "key": "algorithm", "operator": "=", "value": "dfs" },
      { "condition": "AND", "key": "algorithm_substring", "operator": "=", "value": "no_mem_rand" }
     ]
    }
   ]
  },
  {
   "title": "DFS Deeping",
   "type": "table",
   "gridPos": { "h": 18, "w": 6, "x": 5, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "project=n-puzzle",
     "query": "SELECT mean(\"solution_moves\") AS \"Moves\" , count(\"solution_moves\") AS \"Num of solutions\" FROM \"project=n-puzzle\" WHERE (\"puzzle_size\" = '3' AND \"algorithm\" = 'dfs' AND \"algorithm_substring\" = 'deeping_mem') AND $timeFilter GROUP BY time(1h)",
     "select": [
      [
       { "params": [ "solution_moves" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "puzzle_size", "operator": "=", "value": "3" },
      { "condition": "AND", "key": "algorithm", "operator": "=", "value": "dfs" },
      { "condition": "AND", "key": "algorithm_substring", "operator": "=", "value": "deeping_mem" }
     ]
    }
   ]
  },
  {
   "title": "BFS (List)",
   "type": "table",
   "gridPos": { "h": 18, "w": 5, "x": 11, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "project=n-puzzle",
     "query": "SELECT mean(\"solution_moves\") AS \"Moves\" , count(\"solution_moves\") AS \"Num of solutions\" FROM \"project=n-puzzle\" WHERE (\"puzzle_size\" = '3' AND \"algorithm\" = 'bfs' AND \"algorithm_substring\" = 'list') AND $timeFilter GROUP BY time(1h)",
     "select": [
      [
       { "params": [ "solution_moves" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "puzzle_size", "operator": "=", "value": "3" },
      { "condition": "AND", "key": "algorithm", "operator": "=", "value": "bfs" },
      { "condition": "AND", "key": "algorithm_substring", "operator": "=", "value": "mem" }
     ]
    }
   ]
  },
  {
   "title": "BFS (B_Tree)",
   "type": "table",
   "gridPos": { "h": 18, "w": 5, "x": 16, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "project=n-puzzle",
     "query": "SELECT mean(\"solution_moves\") AS \"Moves\" , count(\"solution_moves\") AS \"Num of solutions\" FROM \"project=n-puzzle\" WHERE (\"puzzle_size\" = '3' AND \"algorithm\" = 'bfs' AND \"algorithm_substring\" = 'b_tree') AND $timeFilter GROUP BY time(1h)",
     "select": [
      [
       { "params": [ "solution_moves" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "puzzle_size", "operator": "=", "value": "3" },
      { "condition": "AND", "key": "algorithm", "operator": "=", "value": "bfs" },
      { "condition": "AND", "key": "algorithm_substring", "operator": "=", "value": "mem" }
     ]
    }
   ]
  },
  {
   "title": "DFS (Deeping)",
   "type": "michaeldmoore-scatter-panel",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 18 },
   "targets": [
    {
     "measurement": "project=n-puzzle",
     "select": [
      [
       { "params": [ "solution_moves" ], "type": "field" }
      ],
      [
       { "params": [ "total_cpu_usage_time" ], "type": "field" },
       { "params": [ " / 1000 / 60" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "puzzle_size", "operator": "=", "value": "3" },
      { "condition": "AND", "key": "algorithm", "operator": "=", "value": "dfs" },
      { "condition": "AND", "key": "algorithm_substring", "operator": "=", "value": "deeping_mem" }
     ]
    }
   ]
  },
  {
   "title": "BFS (List)",
   "type": "michaeldmoore-scatter-panel",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 27 },
   "targets": [
    {
     "measurement": "project=n-puzzle",
     "select": [
      [
       { "params": [ "solution_moves" ], "type": "field" }
      ],
      [
       { "params": [ "total_cpu_usage_time" ], "type": "field" },
       { "params": [ " / 1000 / 60" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "puzzle_size", "operator": "=", "value": "3" },
      { "condition": "AND", "key": "algorithm", "operator": "=", "value": "bfs" },
      { "condition": "AND", "key": "algorithm_substring", "operator": "=", "value": "list" }
     ]
    }
   ]
  },
  {
   "title": "BFS (B Tree)",
   "type": "michaeldmoore-scatter-panel",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 36 },
   "targets": [
    {
     "measurement": "project=n-puzzle",
     "select": [
      [
       { "params": [ "solution_moves" ], "type": "field" }
      ],
      [
       { "params": [ "total_cpu_usage_time" ], "type": "field" },
       { "params": [ " / 1000 / 60" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "puzzle_size", "operator": "=", "value": "3" },
      { "condition": "AND", "key": "algorithm", "operator": "=", "value": "bfs" },
      { "condition": "AND", "key": "algorithm_substring", "operator": "=", "value": "b_tree" }
     ]
    }
   ]
  }
 ]
}